name: build-tauri
on: [workflow_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install deps (Windows only)
        if: runner.os == 'Windows'
        run: |
          choco install -y nsis
          # For MSI builds also:
          # choco install -y wixtoolset
      - name: Install JS deps
        run: pnpm install --frozen-lockfile
      - name: Build (macOS DMG)
        if: runner.os == 'macOS'
        run: pnpm tauri build --bundles dmg
      - name: Build (Windows NSIS)
        if: runner.os == 'Windows'
        run: pnpm tauri build --bundles nsis
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-artifacts
          path: |
            src-tauri/target/**/bundle/**
